/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ujikom.GUI;
import Ujikom.Class.koneksi;
import java.util.*;
import java.io.File;
import java.sql.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

 
 
 
public class FrmBeliCash extends javax.swing.JFrame {
JasperDesign jasperdesain;
JasperPrint jasperprint;
JasperReport jasperreport;
    Map<String, Object> param = new HashMap<String, Object>();
    /**
     * Creates new form FrmBeliCash
     */
    public FrmBeliCash() {
        initComponents();
        koneksi.Koneksi_DB();
        setcombomobil();
        setcomboktp();
    }
    public void setcombomobil(){
        try{
        String sql = "select * from mobil";
        koneksi.rs = koneksi.cn.executeQuery(sql);
        while(koneksi.rs.next()){
            KodeMobil.addItem(koneksi.rs.getString(1));
        }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    public void setcomboktp(){
        try{
        String sql = "select * from pembeli";
        koneksi.rs = koneksi.cn.executeQuery(sql);
        while(koneksi.rs.next()){
            NoKTP.addItem(koneksi.rs.getString(1));
        }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    public void settanggal(){
        java.util.Date now = new java.util.Date();
        java.text.SimpleDateFormat call = new java.text.SimpleDateFormat("yyyy-MM-dd");
        Tanggal.setText(call.format(now));
    }
    public void kodeotomatis(){
        try{
            String sql = "select max(right(kode_cash,2)) from beli_cash";
            koneksi.rs = koneksi.cn.executeQuery(sql);
            while(koneksi.rs.next()){
                if(koneksi.rs.first()==true){
                    koneksi.rs.last();
                    int hitung = koneksi.rs.getInt(1)+1;
                    String itung = String.valueOf(hitung);
                    int panjang = itung.length();
                    for(int i=0;i<2-panjang;i++){
                        itung = "00"+hitung;
                    }
                    NoTransaksi.setText("C"+itung);
                }else{
                    NoTransaksi.setText("C01");
                }
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    public void bersih(){
        NoTransaksi.setText(null);
        Tanggal.setText(null);
        KodeMobil.setSelectedItem("Pilih Kode Mobil");
        MerkMobil.setText(null);
        TypeMobil.setText(null);
        WarnaMobil.setText(null);
        HargaMobil.setText(null);
        tampilgambar.setIcon(null);
        NoKTP.setSelectedItem("Pilih No KTP");
        Nama.setText(null);
        Alamat.setText(null);
        NoTelepon.setText(null);
        HarusDibayar.setText(null);
        Dibayar.setText(null);
        Kembali.setText(null);
    }
    public void aktif(){
        KodeMobil.setEnabled(true);
        NoKTP.setEnabled(true);
        Dibayar.setEnabled(true);
    }
    public void nonaktif(){
        KodeMobil.setEnabled(false);
        NoKTP.setEnabled(false);
        Dibayar.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampilgambar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        KodeMobil = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MerkMobil = new javax.swing.JTextField();
        TypeMobil = new javax.swing.JTextField();
        WarnaMobil = new javax.swing.JTextField();
        HargaMobil = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        NoTransaksi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Tanggal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        NoTelepon = new javax.swing.JTextField();
        NoKTP = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        HarusDibayar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Dibayar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Kembali = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pembelian Cash");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PEMBELIAN CASH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gambar"));
        jScrollPane1.setViewportView(tampilgambar);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Mobil");

        KodeMobil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Kode Mobil" }));
        KodeMobil.setEnabled(false);
        KodeMobil.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                KodeMobilItemStateChanged(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Merk");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Type");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Warna");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Harga");

        MerkMobil.setEnabled(false);

        TypeMobil.setEnabled(false);

        WarnaMobil.setEnabled(false);

        HargaMobil.setEnabled(false);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No Transaksi");

        NoTransaksi.setEnabled(false);
        NoTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoTransaksiActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tanggal");

        Tanggal.setEnabled(false);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Pembeli"));

        jLabel9.setText("No KTP");

        jLabel10.setText("Nama Lengkap");

        jLabel11.setText("Alamat");

        jLabel12.setText("No Telepon");

        Nama.setEnabled(false);

        Alamat.setEnabled(false);

        NoTelepon.setEnabled(false);

        NoKTP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih No KTP" }));
        NoKTP.setEnabled(false);
        NoKTP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NoKTPItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(NoTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nama)
                            .addComponent(Alamat)
                            .addComponent(NoKTP, 0, 112, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(NoKTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(NoTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Jumlah yg harus dibayar(Rp)");

        HarusDibayar.setEnabled(false);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Uang Pembayaran(RP)");

        Dibayar.setEnabled(false);
        Dibayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DibayarKeyReleased(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Uang Kembali(RP)");

        Kembali.setEnabled(false);

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Simpan.setText("Simpan Dan Cetak Faktur");
        Simpan.setEnabled(false);
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        jButton3.setText("Batal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Tutup");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NoTransaksi))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(KodeMobil, 0, 98, Short.MAX_VALUE)
                                    .addComponent(MerkMobil)
                                    .addComponent(TypeMobil)
                                    .addComponent(WarnaMobil)
                                    .addComponent(HargaMobil))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tanggal)
                                .addGap(29, 29, 29))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HarusDibayar)
                            .addComponent(jLabel14)
                            .addComponent(Dibayar)
                            .addComponent(jLabel15)
                            .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(NoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(KodeMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(MerkMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TypeMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(WarnaMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(HargaMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HarusDibayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dibayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Simpan)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void KodeMobilItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_KodeMobilItemStateChanged
        // TODO add your handling code here:
        try{
            String sql = "Select * From mobil where kode_mobil = '"+KodeMobil.getSelectedItem()+"'";
            koneksi.rs = koneksi.cn.executeQuery(sql);
            while(koneksi.rs.next()){
                MerkMobil.setText(koneksi.rs.getString("Merk"));
                TypeMobil.setText(koneksi.rs.getString("Type"));
                WarnaMobil.setText(koneksi.rs.getString("Warna"));
                HargaMobil.setText(koneksi.rs.getString("Harga_Mobil"));
                HarusDibayar.setText(koneksi.rs.getString("Harga_Mobil"));
                tampilgambar.setIcon(new ImageIcon(koneksi.rs.getString("Gambar")));
            }
            NoKTP.requestFocus();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_KodeMobilItemStateChanged

    private void NoKTPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NoKTPItemStateChanged
        // TODO add your handling code here:
        try{
            String sql = "Select * From pembeli where ktp = '"+NoKTP.getSelectedItem()+"'";
            koneksi.rs = koneksi.cn.executeQuery(sql);
            while(koneksi.rs.next()){
                Nama.setText(koneksi.rs.getString(2));
                Alamat.setText(koneksi.rs.getString(3));
                NoTelepon.setText(koneksi.rs.getString(4));
            }
            Dibayar.requestFocus();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_NoKTPItemStateChanged

    private void DibayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DibayarKeyReleased
        // TODO add your handling code here:
        int a = Integer.parseInt(HarusDibayar.getText());
        int b = Integer.parseInt(Dibayar.getText());
        int c = a-b;
        Kembali.setText(String.valueOf(c));
    }//GEN-LAST:event_DibayarKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        bersih();
        aktif();
        KodeMobil.requestFocus();
        kodeotomatis();
        settanggal();
        Simpan.setEnabled(true);
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        bersih();
        nonaktif();
        Simpan.setEnabled(false);
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int app;
        if((app= JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan menutup Transaksi Beli Cash?","Tutup",JOptionPane.YES_NO_OPTION))==0){
            this.dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        try{
        String sql = "INSERT INTO beli_cash VALUES("+
                     "'"+NoTransaksi.getText()+"',"+
                     "'"+NoKTP.getSelectedItem()+"',"+
                     "'"+KodeMobil.getSelectedItem()+"',"+
                     "'"+Tanggal.getText()+"',"+
                     "'"+Dibayar.getText()+"')";
        koneksi.cn.executeUpdate(sql);
        JOptionPane.showMessageDialog(null, NoTransaksi.getText()+" Disimpan!");
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        try{
        File file = new File("src/Ujikom/Report/reportBeli.jrxml");
        jasperdesain = JRXmlLoader.load(file);
        param.put("NOFAKTUR", NoTransaksi.getText());
        jasperreport = JasperCompileManager.compileReport(jasperdesain);
        jasperprint = JasperFillManager.fillReport(jasperreport, param,koneksi.conn);
        JasperViewer.viewReport(jasperprint,false);
        bersih();
        nonaktif();
        jButton1.setEnabled(true);
        }catch(Exception e){
        Simpan.setEnabled(false);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_SimpanActionPerformed

    private void NoTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoTransaksiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField Dibayar;
    private javax.swing.JTextField HargaMobil;
    private javax.swing.JTextField HarusDibayar;
    private javax.swing.JTextField Kembali;
    private javax.swing.JComboBox KodeMobil;
    private javax.swing.JTextField MerkMobil;
    private javax.swing.JTextField Nama;
    private javax.swing.JComboBox NoKTP;
    private javax.swing.JTextField NoTelepon;
    private javax.swing.JTextField NoTransaksi;
    private javax.swing.JButton Simpan;
    private javax.swing.JTextField Tanggal;
    private javax.swing.JTextField TypeMobil;
    private javax.swing.JTextField WarnaMobil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tampilgambar;
    // End of variables declaration//GEN-END:variables
}
